### ISSUE TITLE
LIP-5: Pulse (Block Reward Restructure)

### ISSUE THREAD

**Issue by CryptoFirefly** [loki-project/loki-improvement-proposals#9]
> **Block Reward Restructure**
> To implement Pulse, we assume miners have been completely removed from the network, and that mining rewards are either being reallocated to Service Nodes or not created at all. The current logic of sequentially rewarding each Service Node in a sorted list would be preserved, however for a Service Node to win this reward they must act honestly as a leader by producing a valid candidate block.

Opening this issue for the community to provide their inputs, insights and POV on the block reward split if LIP-5 is adopted. Re-distributing the tail emission for Loki and keeping in mind the overall supply and its impact to the project. 

**My 2 Cents.**

Currently _(we are eventually tending to)_ creation of 28 Loki per block, the final tail emission for Loki. 
On an Annual basis that meant (Currently)
50% SN: ---------- 720 x 14 x 365 = 3679200
45% Miners: ------720 x 12.6 x 365 = 3311280
5% Foundation: -- 720 x 1.4 x 365 = 367920
Total: 7358400 new Loki per year

**Reasoning**
1. A successful decentralized project also needs a foundation or body that's sufficiently independent to oversee, steer and govern the actors. It also needs to ensure the real agenda of the chain is kept in check. Sufficient support for LF. 
2. Change in the Block structure should also ensure Nodes that would do a lot more continue to be incentivised.  

**Option 1:** Removing Miner's rewards leaves us at below % break-ups
SN: ----------- 720 x 14 x 365 = 3679200  (90.9%)
Foundation: -- 720 x 1.4 x 365 = 367920  (9.09%)
Total: 4047120 new Loki per year

* This increases the Loki foundation rewards to 9% of tail emission. (thats a big jump from 5%). In absolute terms its not changed, but with much lower inflation its value is surly going to increase. 

**Option 2:** Allocate the Miner's rewards completely to SNs
SN: ----------- 720 x 26.6 x 365 = 6990480  (95%)
Foundation: -- 720 x 1.4 x 365 = 367920  (5%)
Total: 7358400 new Loki per year

* The foundation receives the same absolute value, but the nodes stakers receive all the rewards, nearly doubling the rewards until the no. of SNs increase, which is also limited by the Loki available. With nearly 43% locked in SNs, its very hard to touch 86%, to receive the same absolute Loki per SN. 

**Option 3:** Mid-way. Spread the Benefits across all.
Under this option, major of the benefits can go to the Nodes, as they do the job of producing blocks and are the fundamental backbone and need to have good incentives for a long time or perpetually.  
Update the Block Reward to 24 Loki per block
SN: ----------- 720 x 22.2 x 365 = 5834160 (92.5%)
Foundation: -- 720 x 1.8 x 365 = 473040 (7.5%)
Total: 6307200  new Loki per year

Reduced block reward & tail emission will also benefit those not staking by lower inflation.
Increased reward for the Foundation _(Both % & absolute terms of nearly 100k Loki p.a.)_ will support a longer pipeline and support more marketing and product improvements initiatives. 

Additionally, a rule on the Maximum no. of Foundation nodes should to be reduced to 5% of network for fully managed nodes. While remaining upto 50% of Foundation's Loki allowed to be staked into open shared nodes. Helping decentralization and also allowing LF to earn by staking in shared nodes as they open up. 

Would love to hear more ideas from the rest of the community and the team.

**Comment by KeeJef** [comment]
I am in favor of a eliminating the miner reward with the implementation of Pulse and rebalancing the foundation reward to remain at 5% , with the Service Nodes earning 95%. I don't think the Foundation should be increasing its percentage cut of the block reward if the Pulse fork occurs. 

Elimination of the miner reward seems sensible since it reduces the affect of inflation on the entire Loki community. Reductions in inflation should result in less downwards sell pressure from Service Nodes in the Loki market, if this leads to an increase in price we should also see an increase in the Service Node count. It also reduces the Loki needed to be burned to offset inflation and maintain a healthy, low inflation monetary policy. Reallocation of miner reward to Service Nodes would immediately increase the number of Service Nodes, but would not address some of the more systemic issues with the relatively high inflation rate of Loki.

**Comment by CryptoFirefly** [comment]
Low Inflation: I love that and many months ago i had also shared in the groups that i did feel the 28 Loki tail emission was a bit too high. And was hurting the HODL'ers who don't stake or mine. 
Lower inflation helps retain relative $ value for everyone.

Low Inflation Option: Removing Miner's rewards & LF stays at 5% of block reward
(So that makes it 14.7 Loki per Block)
SN: ----------- 720 x 14 x 365 = 3679200 (95%)
Foundation: -- 720 x 0.7 x 365 = 183960 (5%)
Total: ONLY 3863160 new Loki per year  (< 9% inflation p.a. and dropping perpetually)

I like the above model. Maybe we could look to sweeten it a little with maybe 16 Loki per block instead of the 14.7; and keeping the 95:5 ratio.

**Comment by jpthor** [comment]
Low (<10%) inflation is ideal. 

I'm sucker for nice round numbers:

**Nodes:** 0.9 * 20 = 19 LOKI per block
**LF:** 0.1 * 20 = 1 LOKI per block
(or 19 blocks * 20, 1 block at 1) <-(important to minimise state growth)

20*720*365 = 5,256,000 (~10% inflation)

**Comment by VINCEG-afk** [comment]
LOKI foundation portion should remain the same at 5%. The remaining 95% should go to node owners. I would keep emission the same. Not a fan of constantly changing emission.

**Comment by jpthor** [comment]
Ok, then targeting 5% Foundation:

Nodes: 0.95 * 20 = 19 LOKI per block
LF: 0.05 * 20 = 1 LOKI per block
(or 19 blocks * 20 for Nodes, 1 block at 20 for LF) <-(important to minimise state growth)

20x720x365 = 5,256,000 pa (~10% inflation)

**Comment by Skelaton4** [comment]
My vote would be for 95% SNs and 5% Foundation.

**Comment by Danmcg86** [comment]
I like the 95%-5% split. However, what if it went to 80-20%, but then the loki foundation limited itself to 40 Nodes. That would be a little more decentralized as far as nodes are concerned. Plus the funds for the foundation would not be locked up, giving more flexibility to spending when opportunities come up. I want the marketing and development to continue, and as Loki becomes better adopted, these funds will be important in expanding the project. The DASH and NRG projects have a good treasury model, and Loki could benefit in the same way.

**Comment by CryptoFirefly** [comment]
Danmcg86: the split we talking about is the split of block rewards and not SNs. 
What % should go-to Governance and what % to SNs. And also the absolute amount, weather it should be 28 Loki or 20 Loki or 14.7 Loki per block.

**Comment by Haafingar** [comment]
Low inflation is not possible if we wish to maintain a high node count. In the case where all miners are eliminated, almost all of the inflation will be sent to Service Nodes. Without sufficient rewards to operate, the node count will fall and the level of service that can be provided to future users will be reduced, or the operating cost will go up, further reducing the number of available nodes, which would require a Staking Requirement adjustment. 

To offset this, the hope is that LNS, with a high user base on the messenger, will be enough to sufficiently offset that inflation by burning Loki at the user end.

Deciding what to do with the current emissions scheme in the face of PoS and LNS is actually a very complicated discussion that will probably require another paper to be written on the scheme to ensure that we are making the correct assumptions based on the year of real data that we now have about Service Node behavior on the network.

**Comment by SomethingGettingWrong** [comment]
I am in favor of  95/5 however I think an increase in service node staking requirements is in order. Would it be possible to increase the staking percentage for new nodes at the same ratio as the increase in emission to the new service nodes from the miner's reward that is leaving? 

This would incentivize not unstacking as you would then need to meet the new requirement this would stop older nodes from staking to dump and newer nodes would now require a higher number to stake.  It wouldn't be that the new service nodes are getting a disadvantage it's just the older nodes would be grandfathered in for good behavior. The new staked nodes would however just an increase in pay equal to the increase in staking amount ratio from the previous design.

**Comment by Lucifer1903** [comment]
20 Loki per block 
Low (<10%) inflation

SN: ----------- 720 x 18.5 x 365 = 4,861,800 (92.5%)
Foundation: -- 720 x 1 x 365 = 262,800 (5%)
Loki Funding System: -- 720 x 0.5 x 365 = 131,400 (2.5%)

5% should continue to go to the foundation and 2.5% should go to the Loki Funding System https://docs.loki.network/Governance/LokiFundingSystem/

While the Loki Funding System is being developed the the 2.5% can go to the Foundation.

**Comment by SomethingGettingWrong** [comment]
**Reasoning**

Right now a nod when it cycles down to 15,000 it will stay. and it will get say 10 loki per day! (Depending on node count) if we double the node emission it would go to 20 loki per day (depending on node count)

I just think that if we're doubling emission to service nodes.. we should double the cost  (30,000) vs (15,000)to get a node.. then double the contributors AT THE LEAST maybe even 3x  having like 1 owner each taking up increments of 3,000 and then the rest (staking 3,000) as a contributor with 10 positions
**example**
Have like  1 owner of a node with 30,000 total 

Or 1 owner at 3,000 and then 9 contributors at 3,000 for a total of 30,000 with the owner preselecting for himself as many available spots leaving only 1 3,000 position and staking 27,000 if he desires.

That way if Loki becomes 2.00 each etc.. then to be a contributor only cost 6,000 USD. 
Some people might be able to stake on kucoin are trust kucoin.

The only downside to this is less nodes but at the end of the day its not as much about node count as it is locked percentage from anonymouty i would think? ( maybe im wrong)  The other downside would be less nodes operating... 


However with the fact people are multistaking from the same address  (IN REALITY) its gonna get rid of all the multtiered nodes on one IP... thats not doing anything for anonymouty anyway!

**Comment by Lucifer1903** [comment]
@SomethingGettingWrong The amount of nodes is important, it's not just about locking up the loki. The more nodes on the network the more data can be routed through the mixnet.

I think if we are going to reduce the emissions is should be to 20 from the current 28 as I proposed above (almost ~30% decrease). Then service node stake could also be decreased by ~30% from 15,000 to 10,000.

**Comment by CryptoFirefly** [comment]
I like the 20 Loki emission per Block. With 95/5 for SN/LF.

On the Loki per node, we don't need to go lower than 15000. Even at 15k, we'll be touching nearly 2000 Nodes, next year as that would need only 30 mil Loki, and we'd be close to 50+ mil circulating supply and perpetually increasing supply. And very low Stake per node will make SNs unprofitable, which we don't want. 

One of the ideas to make entry barrier lower for contributors would be to allow upto 5 more contributors. So min amount to contribute drops to 2250 vs 3750 (for non-last) contributor. While Op still fills the min. 25%. But this idea is for 6.0.0 or 7.0.0... for now we are good.

**Comment by VINCEG-afk** [comment]
The problem with reducing staking requirement per node is it could backfire and reduce the amount of nodes if price goes too low.

**Comment by Lucifer1903** [comment]
@CryptoFirefly @VINCEG-afk good points.

I'm okay with keeping SN stake at 15000, allowing 5 or more contributors. With a block reward of 20 (SN 92.5%, Foundation 5%, Loki Funding System 2.5%)

**Comment by Lucifer1903** [comment]
Actually, I've changed mi mind. I agree with haafingar, a paper should be written to make sure we are making the correct assumptions. However I still think we should add the 2.5% for the Loki funding system and leave the foundation at 5%.

**Comment by Lucifer1903** [comment]
Also I would like to suggest an idea on what to do with the mining reward that needs more research.

This idea could help distribute loki to other parties that don't currently run service nodes, increasing the decentralisation of the network.

The 45% that currently goes to miners could go to service nodes but instead of being minted as Loki coins they would be minted as Loki bonds. Loki bonds would be non-divisable and non usable for staking or any service on lokinet. However they would be transferable so that service nodes can sell them.

Why would someone buy a loki bond instead of loki coin? Investment and belief in the future of loki. The loki bonds would eventually unlock and become loki coin, as they have no current use service nodes are incentivised to sell them to people who want a future stake in the system. The incentive to buy them is that they would like be sold cheaper than an equivalent amount of loki depending on how long they are locked for.

The very first loki bond that is minted should only be locked for 1 block before its converted to loki. The second bond should be locked for 2 blocks, the third for 3 blocks and so on. This would mean a week after loki bonds are implemented it would take a week for newly minted bonds to unlock, a month after implementation, they would take a month to unlock, a year after it would take a year. 
More research needs to be done into this part of loki bonds to figure out if there's a limit that needs to be placed on the lock time. We don't want a situation where 10 year loki bonds are so cheap someone can buy them all, wait 10 years and then run a larger percentage of the service node network. 
It would be best if they were locked long enough for service node operators to be incentivised to sell them but not to long that the discount on the price makes it easy for one entity to buy them all.

**Comment by lewisphil** [comment]
I think we should think about what is the ideal situation at the end for the network.  What is the ideal # SNs, how are they distributed geographically / politically, etc.   Then from that ideal, this step should be at least incrementally headed in that direction.  

If the desired result is the greatest # of SNs, I think the cost entry should be lowered, for example.

How about SN have a choice how long to lock up their coins?  If they lock them up longer, the stake is less.  

With that being said, I like the 95%/5% split, and I like the block reward of 20.

**Comment by Shunta-F** [comment]
I support option 2 in the proposal

**Comment by KeeJef** [comment]
Hey guys, I've outlined the exact proposals the Loki Project team / Foundation is discussing over in #10 would appreciate if we move the conversation over there, thanks for setting this issue up @CryptoFirefly
